#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May  5 18:46:49 2019

@author: dietererben
"""
import re

filename = 'scrape.csv'
with open(filename) as f:
    s = f.read()
    
spl = re.split("\\t([A-Z]+( )*)*\\n", s)

spl[0]
spl[9654]

i = 0
j = 0

texts = []
vocabs = []

i = 0

for i in range(3218):
    vocabs.append(spl[(i*3)+1])


for i in range(3218):    
    texts.append(spl[i*3])

d = {'keyword': vocabs, 'texts': texts}

labels, uniques = pd.factorize(df['keyword'])
df['labels'] = labels

f = open('vocab.txt', 'r')
x = f.readlines()
f.close()

df = pd.DataFrame(data=d)

df['dif'] = df['labels'].diff()


df.to_csv('df.csv',index=False)
df.to_excel("output.xlsx")

uniq = list(pd.unique(df['keyword']))


dff = pd.read_excel('df2.xls')